GET http://127.0.0.1:3000/cocktails?price=7.2
###
GET http://127.0.0.1:3000/cocktails/Alice/zutaten

###
DELETE http://127.0.0.1:3000/cocktails/Alice

###
POST http://127.0.0.1:3000/cocktails
content-type: application/json

{
"name":"Hit and Run",
"preis":12.22,
"zubereitung":"eo ipso",
"kid": 1,
"zgid": 1,
"sgid": 1
}

###
PATCH http://127.0.0.1:3000/cocktails/Cinderella
content-type: application/json

{
"preis": 15.00
}